# Generated by Django 4.2.3 on 2023-07-19 19:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0012_remove_tag_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="comment",
            name="post",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="comment",
                to="blog.post",
                verbose_name="Пост, к которому написан",
            ),
        ),
    ]
